#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

env.Append(CPPDEFINES=["GDEXTENSION"])

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["inc/", "../inc"])
sources = Glob("src/*.cpp")
sources.append("../src/evm.c")
sources.append("../src/evm_asm.c")
sources.append("../src/opcodes.c")
sources.append("../src/evm_disasm.c")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "addons/evm/bin/libevm.{}.{}.framework/libevm.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "addons/evm/bin/libevm{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)

